[project]
name = "itertabpfn"
version = "0.1"
dependencies = [
    "pydantic==2.10.5",
    "tabpfn==2.0.1",
    "scikit-learn",
    "pandas",
    "numpy"
    ]


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"